### ISSUE TITLE
Is the following behavior correct?

### ISSUE THREAD

**Issue by mahnunchik** [ben-eb/postcss-merge-rules#1]
Input:
```css
.test-1 {
  margin-top: 10px;
  margin-bottom: 20px;
}

.test-2 {
  margin-top: 10px;
}

.another-test {
  margin-top: 10px;
  margin-bottom: 30px;
}
```

Output:
```css
.test-1 {
  margin-bottom: 20px;
}

.test-1,.test-2 {
  margin-top: 10px;
}

.another-test {
  margin-top: 10px;
  margin-bottom: 30px;
}
```

Css is processed by simple gulp pipeline:
```js
gulp.src('src/*.css')
  .pipe($.postcss([
    require('postcss-merge-rules')
  ]))
  .pipe(gulp.dest('dist'));
```

The first two selectors were merged but the last one was not.

**Comment by ben-eb** [comment]
Possibly not. I'll have to have a look at the logic that dictates whether the rules are safe to merge together or not.

**Comment by mahnunchik** [comment]
It will be great!

I have tested the same input on https://github.com/jakubpawlowicz/clean-css
Selectors became merged.

**Comment by ben-eb** [comment]
I need more time to think about this. It has something to do with the logic that dictates how selectors should be merged; whether moving a property causes an unwanted visual breakage. For example, if you have these properties:

```css
h1 {
  background-repeat: no-repeat;
}
h2 {
  background: url('test.jpg');
  background-repeat: no-repeat;
}
```

In this instance you can't move the `background-repeat` from the second selector into the first one, because it has a shorthand syntax which will then reset the background-repeat value:

```css
h1, h2 {
  background-repeat: no-repeat;
}

h2 {
  /* Now the background is repeating!
  background: url('test.jpg');
}
```

This is one of the reasons why your example is not being merged properly. I am wondering if it is enough to just check for the existence of a shorthand property, because of course `margin-top` and `margin-bottom` are safe to move, but not if a `margin` property exists.

**Comment by mahnunchik** [comment]
Hi @ben-eb 

Thanks for your answer. Please keep me informed about this task.

I find it more useful to have a pre-processor for merging rules than monolithic library.

As an idea, maybe there is sense to:

* First - merge shorthand properties to one property
* Second - merge rules

For your example it would be:
```css
// 1
h1 {
  // or background: no-repeat;
  background-repeat: no-repeat;
}

h2 {
  background: url('test.jpg') no-repeat;
}

// 2
The same
```
So the second phase will assume that the properties are different.
