### ISSUE TITLE
Seems to be merging rules that aren't similar

### ISSUE THREAD

**Issue by dan-gamble** [ben-eb/postcss-merge-rules#14]
Compiled CSS before cssnano:
```css
.btn-Primary {
  display: inline-block;
  padding-top: 7px;
  padding-right: 20px;
  padding-bottom: 7px;
  padding-left: 20px;
  font-family: 'proxima-nova', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.625rem;
  background-color: transparent;
  border: 2px solid transparent;
  border-radius: 4px;
  color: #fff;
  -webkit-transition: background-color 0.18s, color 0.18s 0.18s;
  transition: background-color 0.18s, color 0.18s 0.18s;
  background-color: transparent;
  border: 2px solid #00bbd3;
  color: #00bbd3;
}
.btn-Primary:hover {
  background-color: transparent;
  color: #fff;
}
.btn-Primary:hover {
  background-color: #00bbd3;
  color: #fff;
}
.btn-Secondary {
  display: inline-block;
  padding-top: 7px;
  padding-right: 20px;
  padding-bottom: 7px;
  padding-left: 20px;
  font-family: 'proxima-nova', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.625rem;
  background-color: transparent;
  border: 2px solid transparent;
  border-radius: 4px;
  color: #fff;
  -webkit-transition: background-color 0.18s, color 0.18s 0.18s;
  transition: background-color 0.18s, color 0.18s 0.18s;
  background-color: transparent;
  border: 2px solid #00bbd3;
  color: #fff;
}
.btn-Secondary:hover {
  background-color: transparent;
  color: #fff;
}
.btn-Secondary:hover {
  background-color: #00bbd3;
  color: #fff;
}
```

Compiled CSS after cssnano:
```css
.btn-Primary {
    display: inline-block;
    padding: 7px 20px;
    font-family: proxima-nova, Helvetica Neue, Helvetica, Arial, sans-serif;
    font-size: 1rem;
    font-weight: 600;
    line-height: 1.625rem;
    border: 2px solid transparent;
    border-radius: 4px;
    color: #fff;
    -webkit-transition: background-color .18s, color .18s .18s;
    transition: background-color .18s, color .18s .18s;
    background-color: transparent;
    border: 2px solid #00bbd3;
    color: #00bbd3
}
.btn-Primary:hover {
    background-color: #00bbd3
}
.btn-Primary:hover,
.btn-Secondary {
    background-color: transparent;
    color: #fff
}
.btn-Secondary {
    display: inline-block;
    padding: 7px 20px;
    font-family: proxima-nova, Helvetica Neue, Helvetica, Arial, sans-serif;
    font-size: 1rem;
    font-weight: 600;
    line-height: 1.625rem;
    border: 2px solid transparent;
    border-radius: 4px;
    -webkit-transition: background-color .18s, color .18s .18s;
    transition: background-color .18s, color .18s .18s;
    border: 2px solid #00bbd3
}
.btn-Secondary:hover {
    background-color: transparent;
    color: #fff;
    background-color: #00bbd3
}
```

It seems to be merging `.btn-Secondary` & `.btn-Primary:hover` even though they have different styles

**Comment by rozzzly** [comment]
Looks like it's pulling the first definition of `.btn-Primary:hover` and merging that with `.btn-Secondary`'s `background-color` and `color` properties. They might be different ~~styles~~ selectors, but that's what the plugin is supposed to: find common properties and merge them. 

But all of that's beyond the point. Why do you have duplicate selector definitions like this?
```css
.btn-Primary:hover {
  background-color: transparent;
  color: #fff;
}
.btn-Primary:hover {
  background-color: #00bbd3;
  color: #fff;
}
```
the browser is just going to merge the two itself (lower definitions overwriting higher ones). The issue you're seeing is because of improper parsing of duplicate definitions, but I'd say that's less of an issue than your the structure of the code you're passing it.

**Comment by jhnns** [comment]
I can confirm this. This is a minimal example ([Gist](https://gist.github.com/jhnns/0473ee2c022b12e507b3)):

```css
/* in.css */
.a {
    font-family: Arial;
    font-family: Helvetica;
}

.b {
    font-family: Arial;
}
```

```css
/* out.css */
.a{font-family:Helvetica}.a,.b{font-family:Arial}
```

As you can clearly see: `out.css` will assign `.a` another font as it used to have.

Sure, you can argue that `in.css` is not "good css" anyway, but this situation can easily arise when overriding mixins. Imho it doesn't matter whether the given CSS is bad or good, the transform is destructive in this case which should not be.

**Comment by elektronik2k5** [comment]
+1

**Comment by sgoll** [comment]
We have been bitten by this as well. Actual minimal example:

```css
.alpha { overflow: hidden; overflow-y: auto }
.beta { overflow: hidden }
```

This produces the following, semantically not equivalent, CSS when run through `cssnano` (formatted verbosely here to better illustrate differences):

```css
.alpha { overflow-y: auto }
.alpha, .beta { overflow: hidden }
```

For now, we are working around this by disabling `mergeRules` but it would be great if we could enable it again.

For the meantime, I suggest marking `postcss-merge-rules` as potentially unsafe: without intrinsic knowledge about which CSS rules (potentially) override other CSS rules, it seems to be impossible to automatically partially merge in this case because either way we are changing the order of CSS rules.

The general case would only be possible if all CSS rules in question kept their respective positions, such as in the following input (where `.alpha` und `.beta` changed order but are otherwise the same):

```css
.beta { overflow: hidden }
.alpha { overflow: hidden; overflow-y: auto }
```

This could safely be merged to produce the following:

```css
.beta, .alpha { overflow: hidden }
.alpha { overflow-y: auto }
```

Would it make sense to limit `postcss-merge-rules` to the cases where it can guarantee that rules are not changed in their order, and have another plugin normalize the order of rules according to some metric (while keeping the CSS equivalent, i.e. with the required knowledge which rules influence each other) before handing it over to `postcss-merge-rules`?

**Comment by MethodGrab** [comment]
+1! Another case where it causes problems is rgba fallbacks. In the below example the background color will always be 100% white, never 50% white.

```scss
// source.scss
div {
	background-color: #fff;
	background-color: rgba( #fff, 0.5 );

	&:hover {
		background-color: #fff;
	}
}
```

```css
/* output.css */
div { background-color: hsla(0, 0%, 100%, .5) }
div, div:hover { background-color: #fff }
```
