### ISSUE TITLE
Don't merge rules with vendor-specific pseudo-element selectors 

### ISSUE THREAD

**Issue by martijnvermaat** [ben-eb/postcss-merge-rules#18]
It's nice that apparently corresponding vendor-specific pseudo-element selectors are recognized, but they really shouldn't be merged.

For example, in the following CSS:
```css
input[type=range] {
  -webkit-appearance: none !important;
}

input[type=range]::-webkit-slider-runnable-track {
  height: 2px;
  width: 100px;
  background: red;
  border: none;
}

input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none !important;
  border: none;
  width: 10px;
  height: 10px;
  background: red;
}

input[type=range]::-moz-range-thumb {
  border: none;
  width: 10px;
  height: 10px;
  background: red;
}
```
the last two rules are translated into the following:
```css
input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none!important
}

input[type=range]::-moz-range-thumb,
input[type=range]::-webkit-slider-thumb {
  border: none;
  width: 10px;
  height: 10px;
  background: red
}
```

However, since any given browser will not recognize at least one of the selectors, the entire rule is ignored (this is [by spec](http://stackoverflow.com/questions/16982449/why-isnt-it-possible-to-combine-vendor-specific-pseudo-elements-classes-into-on)).

Live example where we can see the rendering is different in both Firefox and Chrome:

https://rawgit.com/martijnvermaat/81eb2945b36657aa9528/raw/6409494c0daee2cea59270eaa8b36a8693d421c7/index.html
