### ISSUE TITLE
Wrong order when partially merging rules with specializing records

### ISSUE THREAD

**Issue by 11bit** [ben-eb/postcss-merge-rules#20]
There is a (seems to be) wrong behaviour when mergin two rules of this type:

```
.foo {
    margin: 0;
    margin-left: 30px;
} 

.bar {
    margin: 0;
    margin-right: 30px;
}
```

Which is converted to:

```
.foo {
    margin-left: 30px; /* will be overwriten by next rule */
}

.foo,.bar {
    margin: 0;
}

.bar {
    margin-right: 30px;
}
```
Left margin here will be lost.

Are there any reasons to keep merged rule after first one? Pushing merged rule before first and second looks like an easiest solution which will solve many order problems but I don't know css enough to predict what can go wrong.

**Comment by futpib** [comment]
This looks like a duplicate of #13 to me. Seems that preserving original order of properties is the right way to go.

"Always push before"-strategy may be subverted just as easily:
```css
.foo {
    margin-left: 30px;
    margin: 0;
} 

.bar {
    margin-right: 30px;
    margin: 0;
}
```
Which will be converted to:
```css
.foo,.bar {
    margin: 0;
}

.foo {
    margin-left: 30px;
}

.bar {
    margin-right: 30px;
}
```
