### ISSUE TITLE
flebox: Wrongly splits and merges rules that overwrite themselves

### ISSUE THREAD

**Issue by TN1ck** [ben-eb/postcss-merge-rules#21]
I created a flexbox-grid, and thus had classes that looked like this:

```css
.fb-col-md-6 {
   ...
   flex: 0 0 auto;
   flex-basis: 50%;
}
.fb-col-md-7 {
   ...
   flex: 0 0 auto;
   flex-basis: 58.3%;
}
```
Problem was, that the merge rules created:

```css
.fb-col-md-6, .fb-col-md-7 {
   ...
   flex: 0 0 auto;
}
```

```css
.fb-col-md-6 {
   flex-basis: 50%;
}

.fb-col-md-7 {
   flex-basis: 58.3%;
}
```

This broke the grid, because `flex-basis: xx%` was not applied, because `flex: 0 0 auto` also specifies it.
