### ISSUE TITLE
No new selector created

### ISSUE THREAD

**Issue by vojtatranta** [ben-eb/postcss-merge-rules#39]
Hi, thank you for this awesome tool. I have one simple improvement.

Consider this input:
```css
.modal--variable {
    width: auto;
    height: 20px;
    font-weight: 300;
}

.modal-tab__content--stretched {
    height: 20px;
    width: auto;
    font-weight: bold;
}
```
I would expect this output:
```css
.modal--variable, .modal-tab__content--stretched {
    width: auto;
    height: 20px;
}

.modal--variable {
  font-weight: bold;
}

.modal-tab__content--stretched {
    font-weight: bold;
}
```

Actual output is however same as original.

Even thought the expected output is bigger in character in beautiful version than original, when you minify it, you get smaller bundle. It would be even better when selectors are minified.

What do you think?
