### ISSUE TITLE
Merging removes wrong property

### ISSUE THREAD

**Issue by m-blank** [ben-eb/postcss-merge-rules#40]
Hi @ben-eb. 
If I try to minify the following code with cssnano (`mergeRules` option turned on), the plugin is removing the property `color` in the second rule instead of the overridden property `background-color` in the first rule.

**input.css**

```css
.a
{
    background-color: #fff;
}

.a
{
    background-color: #717F83;
    color: #fff;
}
```

**output.css**

```css
.a{background-color:#fff;background-color:#717f83}
```

As you can see, I'm left with the duplicate properties `background-color` and the `color` property is gone.

**expected output:**

```css
.a{background-color:#717f83;color:#fff}
```

To reproduce this error, I've installed the cssnano-cli using npm:

`npm install cssnano-cli -g`
`cssnano < input.css > output.css`
