### ISSUE TITLE
Bug affecting selector hacks.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/postcss-merge-rules#5]
Ref: https://github.com/ben-eb/cssnano/issues/33

```css
.classA {
  *zoom: 1;
}
.classB {
  box-sizing: border-box;
  position: relative;
  min-height: 100%;
}
.classC {
  box-sizing: border-box;
  position: relative;
}
.classD {
  box-sizing: border-box;
  position: relative;
}
```

Output:

```css
.classA{zoom:1}.classB{min-height:100%}.classB,.classC{box-sizing:border-box;*position:relative}.D{box-sizing:border-box;position:relative}
```

**Comment by ben-eb** [comment]
Fixed in `1.3.3`. This set of rules will now output:

```css
.classA{*zoom:1}.classB{min-height:100%}.classB,.classC,.classD{box-sizing:border-box;position:relative}
```

**Comment by buzinas** [comment]
I think this bug isn't completely solved:

Input:

```css
a {
  padding-left: 8px;
  padding-right: 8px;
  *padding-top: 5px;
  *padding-bottom: 5px;
}
```

Output

```css
a{padding:5px 8px;}
```
