### ISSUE TITLE
Smarter merge?

### ISSUE THREAD

**Issue by dv** [ben-eb/postcss-merge-rules#50]
I have some css from a grid that looks like this:

```css
  td.small-1 {
    display: inline-block !important; width: 4.16667% !important;
  }
  th.small-1 {
    display: inline-block !important; width: 4.16667% !important;
  }
  td.small-2 {
    display: inline-block !important; width: 8.33333% !important;
  }
  th.small-2 {
    display: inline-block !important; width: 8.33333% !important;
  }

// ... (up to .small-24)
```

As you can see, there's a common `display` and a different width for each. The way `postcss-merge-rules` merges these are as follows:

```css
  td.small-1,th.small-1 {
    display: inline-block !important; width: 4.16667% !important;
  }
  td.small-2,th.small-2 {
    display: inline-block !important; width: 8.33333% !important;
  }

// ...
```

Which is fine and dandy, however it's not the most optimal. The best merging would be as follows, extracting `display` into one term, and then having the seperate `width`s:

```css
td.small-1, th.small-1, td.small-2, th.small-2, .... {
  display: inline-block !important;
}

td.small-1,th.small-1 {
  width: 4.16667% !important;
}
td.small-2,th.small-2 {
  width: 8.33333% !important;
}

// ...
```

This would create a more minified version. Is it possible for `postcss-merge-rules` to merge it in this way?
