### ISSUE TITLE
In some cases it not merge.

### ISSUE THREAD

**Issue by hilquiasrodrigues** [ben-eb/postcss-merge-rules#6]
When you run the merge at this code below you will get the same code.
``` css
body {
  font-family: Arial, sans-serif;
  color: #000;
  font-size: 12px;
}
a {
  font-weight: bold;
  text-decoration: none;
}
body {
  margin: 0;
  padding: 0;
}
```
The output should be like this. Shouldn't it ?
``` css
body {
  font-family: Arial, sans-serif;
  color: #000;
  font-size: 12px;
  margin: 0;
  padding: 0;
}
a {
  font-weight: bold;
  text-decoration: none;
}
```
