### ISSUE TITLE
Merging non-adjacent rules

### ISSUE THREAD

**Issue by reubn** [ben-eb/postcss-merge-rules#7]
A useful feature to include would be the ability to merge non-adjacent rules. As this could potentially be unsafe and affect the overall effect of the CSS, it could be enabled via a configuration flag.

Just a suggestion

**Comment by ben-eb** [comment]
PRs welcome, but I have a few other ideas for 'safe' optimisations before I get to this.

**Comment by reubn** [comment]
That's fine :)

**Comment by Yimiprod** [comment]
Came for this. Not disapointed.

**Comment by ben-eb** [comment]
@Yimiprod PR still welcome. :smile:

**Comment by Dylan-Chapman** [comment]
+1

**Comment by corysimmons** [comment]
"Safe"?

Don't people `input-safe.css` -> `output-altered.css`? How could anything in PostCSS be unsafe?

I would love to see this feature happen...

Just look at all the compiled repetition: http://codepen.io/corysimmons/pen/jWzVOx?editors=1100

Now imagine you have a site with dozens of grid declarations and media queries on it...

I don't know how to battle this problem from my end.

**Comment by ben-eb** [comment]
Potentially re-ordering rules in the CSS file can break the semantics of the CSS as you are changing the order in which rules are applied. This might lead to unexpected breakage just because of rule order.

**PRs are still welcome**.

**Comment by corysimmons** [comment]
Is this issue or repo about re-ordering rules? I thought it was about merging rules.

```css
a { color: red; font-family: serif; }
a { color: blue; }
```
should merge into
```css
a { color: blue; font-family: serif; }
```

**Comment by ben-eb** [comment]
We're talking about *non-adjacent* rules.

```css
h1 { color: red }
h2 { color: black }
h3 { color: green }
h4 { color: yellow }
h5 { color: red }
```

In order to merge properly, the first rule must be moved.

```css
h2 { color: black }
h3 { color: green }
h4 { color: yellow }
h1, h5 { color: red }
```

**Comment by corysimmons** [comment]
Ah, I see what you're saying now. Hm..

**Comment by corysimmons** [comment]
If this does get implemented by anyone, I'd suggest a second option for merge type.

`merge-direction: up`
```css
a {
  color: blue;
}
a {
  color: red;
}
```
should produce
```css
a {
  color: blue;
}
```

Maybe a third option like `media-queries: outside`

```css
.col {
  float: left;
  width: 100%;
}
@media (min-width: 700px) {
  .col {
    float: left;
    width: 50%;
  }
}
```
should produce
```css
.col {
  float: left;
  width: 100%;
}
@media (min-width: 700px) {
  .col {
    width: 50%;
  }
}
```

Just spitballing here.

**Comment by stevenvachon** [comment]
This would be really useful for grid libraries where order probably doesn't matter.

**Comment by stevenvachon** [comment]
Perhaps it could take a list of regular expressions to limit what it's applied to:
```js
mergeNonAdjacentRules: false  // none
// or
mergeNonAdjacentRules: true  // all
// or
mergeNonAdjacentRules: [/\.col-\d+/];  // only .col-#
```

**Comment by corysimmons** [comment]
> This would be really useful for grid libraries where order probably doesn't matter.

That's exactly what I need it for. That's the only consistent complaint I get about my grid systems and there isn't much I can do about it, especially when it gets into media queries. :(

Regex would be cool.

This stuff might be a bit ambitious though. :O

**Comment by lucpotage** [comment]
+ 1 for this feature.

Today, I use maps that is the only way to achieve the same result.

`$h1: (
  color: blue,
  margin: 0
);

$h1: map-merge($h1,
  (
    color: red
  )
);

h1 {
 @each $property, $value in $h1 {
    #{$property}: $value;
  }
}`

This is nice if you work with small projects.
Unfortunately, when you need this feature, it's actually because you work on big projects and specific customizations according to your targeted environment.

Plus, this forces me to write code that is not CSS, which means any I would have to refactor all my maps if the situation is brighter in the future with SASS improvements.
And the function map-merge does not work well with nested maps.

So today, I didn't find any way to merge these rules with pure CSS and post processors.

**Comment by corysimmons** [comment]
@lucpotage I've just been using css-clean + https://github.com/mrcoles/cssunminifier

**Comment by lucpotage** [comment]
Yes, I tried this tool along with cssnano whichi is great too.
But it seems I can't get the result I except with my example above.

    h1 {
      color: green;
      margin: 10px;
    }
    
    h1 {
      color: red;
    }

This code will turn into that code with clean-css:

    h1 {
      color: green;
      margin: 10px;
      color: red;
    }

This is nice but I would like to achieve that result:

    h1 {
      color: red;
      margin: 10px;
    }

Are you saying this is actually possible to do this with clean-css?

**Comment by corysimmons** [comment]
Yeah I'm pretty sure. Try it.

**Comment by lucpotage** [comment]
Thank you for your help! It helps me a lot. It does exactly what I want.
Weirdly, it is said that **gulp-clean-css** is deprecated in favor of _gulp-minify-css_. So I tested the second one and it worked as well. But for **gulp-minify-css**, it's written that the package is deprecated in favor of **cssnano** that offers more advanced options. But it's the one I already use today, so I was very suprised.

Despite several available optimizations, I didn't find a way to get the same result with _cssnano_ as the one with _gulp-minify-css_ or _gulp-clean-css_, maybe because _cssnano_ does not rely on _clean-css_. If eventually you have the answer.

**Comment by saiichihashimoto** [comment]
The `true`/`false`/regex would be amazing! I also use `postcss-import` and it would be really interesting if there was a way that each imported file could decide what nonadjacent rules it would be ok with merging... maybe through comments with the same `true`/`false`/regex values?

**Comment by donabrams** [comment]
I'd love a flag to allow merge/split non-adjacent. Wrote about it here: https://medium.com/@DonTAbrams/immutable-css-optimizing-performance-and-minimizing-size-7547d98abfee

**Comment by cedon** [comment]
I would love to see non-adjacent combining though if the selector is the same. 

For example: 

```css
h1 { color: blue;}
p { color: red; }
h1 { font-size: 2.5rem; }
p { font-size: 1.125rem; }
```
become:

```css
h1 { color blue; font-size: 2.5rem; }
p { color: red; font-size: 1.125rem; }
```

In terms of any conflicts such as a later `h1 { color: green; }`, the last value trumps.
